sdf_derive_census_vars <- function(data) {
  
  data <- data %>%
    mutate(country = "England",
           all = "All people",
           sex = case_when(sex == 1 ~ "Female",
                           sex == 2 ~ "Male"),
           age_group = case_when(resident_age < 5 ~ "<5",
                                 between(resident_age, 5, 16) ~ "5_to_16",
                                 between(resident_age, 17, 24) ~ "17_to_24",
                                 between(resident_age, 25, 34) ~ "25_to_34",
                                 between(resident_age, 35, 44) ~ "35_to_44",
                                 between(resident_age, 45, 54) ~ "45_to_54",
                                 between(resident_age, 55, 64) ~ "55_to_64",
                                 between(resident_age, 65, 74) ~ "65_to_74",
                                 between(resident_age, 75, 84) ~ "75_to_84",
                                 resident_age >= 85  ~ ">=85"),
           age_group_esp = case_when(resident_age < 1 ~ "<1",
                                     between(resident_age, 1, 4) ~ "1-4",
                                     between(resident_age, 5, 9) ~ "5-9",
                                     between(resident_age, 10, 14) ~ "10-14",
                                     between(resident_age, 15, 19) ~ "15-19",
                                     between(resident_age, 20, 24) ~ "20-24",
                                     between(resident_age, 25, 29) ~ "25-29",
                                     between(resident_age, 30, 34) ~ "30-34",
                                     between(resident_age, 35, 39) ~ "35-39",
                                     between(resident_age, 40, 44) ~ "40-44",
                                     between(resident_age, 45, 49) ~ "45-49",
                                     between(resident_age, 50, 54) ~ "50-54",
                                     between(resident_age, 55, 59) ~ "55-59",
                                     between(resident_age, 60, 64) ~ "60-64",
                                     between(resident_age, 65, 69) ~ "65-69",
                                     between(resident_age, 70, 74) ~ "70-74",
                                     between(resident_age, 75, 79) ~ "75-79",
                                     between(resident_age, 80, 84) ~ "80-84",
                                     between(resident_age, 85, 89) ~ "85-89",
                                     resident_age >= 90  ~ "90+"),
           ethnicity_agg = case_when(ethnic05_20 == 1 ~ "White",
                                     ethnic05_20 == 2 ~ "Mixed",
                                     ethnic05_20 == 3 ~ "Asian",
                                     ethnic05_20 == 4 ~ "Black",
                                     ethnic05_20 == 5 ~ "Other",
                                     ethnic05_20 == -8 ~ "No Code Required"),
           heating_type = case_when(heating_type == 1 ~ "No central heating",
                                    heating_type == 2 ~ "Mains gas only",
                                    heating_type == 3 ~ "Tank or bottled gas only",
                                    heating_type == 4 ~ "Electric (including storage heaters) only",
                                    heating_type == 5 ~ "Oil only",
                                    heating_type == 6 ~ "Wood (for example, logs, waste wood or pellets) only",
                                    heating_type == 7 ~ "Solid fuel (including coal) only",
                                    heating_type == 8 ~ "Renewable energy (for example, solar thermal or heat pumps) only",
                                    heating_type == 9 ~ "District or communal heat networks only",
                                    heating_type == 10 ~ "Other central heating only",
                                    heating_type == 11 ~ "Two or more types of central heating (not including renewable energy)",
                                    heating_type == 12 ~ "Two or more types of central heating (including renewable energy)",
                                    heating_type == -9 ~ "Missing"),
           heating_type_agg = case_when(heating_type == "No central heating" ~ "No central heating",
                                        TRUE ~ "Other"),
           disability = case_when(disability == 1 ~ "Yes - reduced a lot",
                                  disability == 2 ~ "Yes - reduced a little",
                                  disability == 3 ~ "Yes - not reduced at all",
                                  disability == 4 ~ "No",
                                  disability == -8 ~ "Code not required"),
           disability_agg = case_when(disability %in% c("Yes - reduced a lot",
                                                        "Yes - reduced a little",
                                                        "Yes - not reduced at all") ~ "Yes",
                                      TRUE ~ "No"),
           health_in_general = case_when(health_in_general == 1 ~ "Very good health",
                                         health_in_general == 2 ~ "Good health",
                                         health_in_general == 3 ~ "Fair health",
                                         health_in_general == 4 ~ "Bad health",
                                         health_in_general == 5 ~ "Very bad health",
                                         health_in_general == -8 ~ "Code not required"),
           activity_last_week = case_when(activity_last_week == 1 ~ "Working",
                                          activity_last_week == 2 ~ "Unemployed",
                                          activity_last_week == 3 ~ "Economically inactive- student",
                                          activity_last_week == 4 ~ "Economically inactive- retired",
                                          activity_last_week == 5 ~ "Economically inactive- long term sick or disabled",
                                          activity_last_week == 6 ~ "Economically inactive- looking after home/family",
                                          activity_last_week == 7 ~ "Economically inactive- other",
                                          activity_last_week == -8 ~ "Not required"),
           activity_last_week_agg = case_when(
             activity_last_week %in% c("Economically inactive- student",
                                       "Economically inactive- retired",
                                       "Economically inactive- long term sick or disabled",
                                       "Economically inactive- looking after home/family",
                                       "Economically inactive- other") ~ "Economically inactive",
             TRUE ~ activity_last_week)) %>%
    rename(region = rgn22nm)
  
  return(data)
  
}